[project]
name = "product_search_category_attribute"
version = "16.0.20240906.0"
dependencies = [
    "odoo-addon-product_name_with_attributes>=16.0dev,<16.1dev",
    "odoo-addon-product_old_migration_fields>=16.0dev,<16.1dev",
    "odoo-addon-product_search_category_attribute>=16.0dev,<16.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 16.0",
]
